### ISSUE TITLE
Integrated into the LSP plugin

### ISSUE THREAD

**Issue by jgmdev** [vqns/lite-xl-snippets#1]
This is more a notification and thank you note than a real issue.

Thanks a lot for developing this plugin (you are a hero), finally integrated it into the LSP plugin on this commit, hopefully I got it right :)

https://github.com/lite-xl/lite-xl-lsp/commit/ca01472a2bc256889ece245f59d17a3fe7cddf2a

**Comment by vqns** [comment]
nice! There may still be a few bugs left, so let me know if you run into any issues :)

edit: reading through your changes, i noticed that you manually set the selection and then call `snippets.execute`. If this is to remove the partial trigger, this is not needed and you can just do `snippets.execute(snippet, nil, true)` and it'll remove it.

[init.lua L523](https://github.com/lite-xl/lite-xl-lsp/blob/6b9baca7e9e09da2e14fb30ee520430806680279/init.lua#L523)

**Comment by jgmdev** [comment]
> edit: reading through your changes, i noticed that you manually set the selection and then call `snippets.execute`. If this is to remove the partial trigger, this is not needed and you can just do `snippets.execute(snippet, nil, true)` and it'll remove it.
> 
> [init.lua L523](https://github.com/lite-xl/lite-xl-lsp/blob/6b9baca7e9e09da2e14fb30ee520430806680279/init.lua#L523)

Just noticed that edit, github, doesn't notifies of edits :(, will test your recommendation later. By the way I will be maintaining this repo now https://github.com/pragtical/lsp

**Comment by vqns** [comment]
@jgmdev  I'm closing the issue but I'll also use this to ask you, what's your stance (with pragtical) on backwards compatibility with lite-xl, at least regarding the core/* api?

**Comment by jgmdev** [comment]
> what's your stance (with pragtical) on backwards compatibility with lite-xl, at least regarding the core/* api?

The goal is to keep the Lua core compatible as long as it is feasible for easier cherry picking any convenient fixes or new features done on Lite XL as for plugins compatibility. But, will not hesitate to introduce differences or fixes when needed like the project rework that was introduced ahead of Lite XL, which required some plugins to be adjusted (adjustments I did to all affected plugins I have access to) or the CLI API https://github.com/pragtical/pragtical/pull/28 for which as things seem we may have a different interface than the solution that may get implemented in Lite XL. 

Also Pragtical as explained on Readme will have LuaJIT first support and provide additional API's when convenient as already been done (threading, encoding, etc...) and which so far hasn't affected backwards compatibility.
