### ISSUE TITLE
Snippet not exit on cursor outside region.

### ISSUE THREAD

**Issue by jgmdev** [vqns/lite-xl-snippets#3]
This one has been reported by some users on discord. Not sure how hard this would be to implement, but currently the snippet doesn't exits even if I move the cursor outside of the snippet region as shown on the video which causes the undesired effect when pressing `tab` to move back on next snippet position as shown on video:

https://github.com/vqns/lite-xl-snippets/assets/1702572/a1e2563e-fad3-43fe-90f5-04058a689982

**Comment by vqns** [comment]
Yeah this is something that I've wanted to add for a while now. There's just a bit of refactoring needed first so hopefully soon:tm:

**Comment by Kabcorp** [comment]
@vqns Got any news about this issue?

**Comment by vqns** [comment]
Sorry, I've been pretty much afk for the past few months. The code has actually been sitting on my local branch for a while now, so probably over the next couple of days

**Comment by vqns** [comment]
Took a while, but 910084e827d9b5ac9d58d1c363f4f1b5c512e39c should do it. It's unfortunately a bit more hacky than I'd like; it only disables jumping to the next or previous tabstops if the leading selection isn't itself on a tabstop. It actually exits only when the doc is modified (insertion / removal) so let me know if it doesn't work.

**Comment by Kabcorp** [comment]
Thank you, I'll try later.
What about adding a setting to completely disable TAB switch feature?

**Comment by vqns** [comment]
> What about adding a setting to completely disable TAB switch feature?

For that, you could just unbind the command in your config:

    local keymap = require 'core.keymap'
    keymap.unbind('tab', 'snippets:next')

or any other of the default bindings that you don't want

**Comment by Kabcorp** [comment]
Thank you

**Comment by Kabcorp** [comment]
And an option to disable function parameters auto-write?
like:
"mems" TAB become "memset(void * pointer, int value, size_t count)"
and removing parameters auto-write will do "memset" or "memset()" only

**Comment by vqns** [comment]
It doesn't do any analysis like function vs variable vs parameters, etc. If you just want the function identifier, regular autocomplete should do it
