### ISSUE TITLE
bash if statement issue with square brackets.

### ISSUE THREAD

**Issue by archusXIV** [vqns/lite-xl-snippets#5]
Hi, first of all thanks for providing snippets in the great lite-xl editor.
I'm having problems adding square brackets like in bash if statements, they seem to close the template block too early and the snippet doesn't work even I escape them.
Here is my vscode snippet:
```
"myIfStatement": {
	"prefix": "myif",
	"body": [
		"if [[ ${1:condition} ]]; then",
		"    ${2:command1}",
		"else",
		"    ${3:command2}",
		"fi"
	],
	"description": "if statement"
}
```
How  can I resolve this issue? Regards.

**Comment by vqns** [comment]
Can't reproduce with this exact snippet. Just so we're on the same page, you're adding it through a json file? Does the snippet trigger but is cut short, or is it not loaded at all?

**Comment by archusXIV** [comment]
Sorry for the confusion (this is what it looks like in vscode), it does not trigger but only autocomplete the word 'myIf' and I don't import snippets from a json file but from a custom plugins:
```
-- mod-version:3
local lsp_snippets = require 'plugins.lsp_snippets'
local snippets = require 'plugins.snippets'

snippets.add {
    trigger  = 'myIf',
    info     = 'if else statement',
    format   = 'lsp',
    template = [[
if [[ ${1:condition} ]]; then
    ${2:command1}
else
    ${3:command2}
fi
]]
}
```
Other than that, case statements, for and while loops, etc... are fine. This is why I suspect the brackets to cause the issue.
I hope you see what I mean, thx again.

**Comment by vqns** [comment]
Yeah it makes sense that it doesn't work in that case. Double brackets (`[[ ... ]]`) is the syntax for literal strings, which end on the first closing delimiter. Here that means the string for the template ends on the test's closing brackets. To avoid this, you can use any number of equals (`=`) between the brackets; that will change the delimiter used to match the end of the string. e.g:

    template = [=[ [[ ]] ]=]
    template = [=====[ [[ ]] ]=====]

See here: https://www.lua.org/manual/5.4/manual.html#3.1

**Comment by archusXIV** [comment]
Ok gonna test your advice and I'll close the issue if it works.
Thxs.

**Comment by archusXIV** [comment]
Great, it works! Again thank you for that plugin, for a bash lover and lite-xl fan this is a +.
