### ISSUE TITLE
LSP-style snippets with no placeholder value

### ISSUE THREAD

**Issue by Guldoman** [vqns/lite-xl-snippets#6]
LSP-style snippets with empty placeholder values produce unexpected outputs.

For example the snippet
```
test(${1:})
```
Produces:
```
test(})
```
with `}` selected.

I'm not sure if this is a valid snippet format, but for example the `gopls` LSP seems to generate those.

**Comment by vqns** [comment]
Yeah empty placeholders are valid. Those were actually parsed but incorrectly set the closing `}` as the placeholder value. Should be fixed by [87248a2](https://github.com/vqns/lite-xl-snippets/commit/87248a23c8ceb2507f46b3ca3689b32d35c9c709).

**Comment by Guldoman** [comment]
Awesome, thank you!
